### ISSUE TITLE
Need help replicating the example code

### ISSUE THREAD

**Issue by sauravm8** [pipizhaoa/Pandalyst#1]
Really excited about this project. However, I am facing difficulty getting the example code to run with the error. 

`cannot import name 'infer' from 'infer' `

Any pointers on the infer package that the example code is using?

**Comment by zhengyanzhao1997** [comment]
we have provide the infer.py in our project.
Please first clone this project and ```cd Pandalyst``` then run the example.

**Comment by pipizhaoa** [comment]
we have provide the infer.py in our project.
Please first clone this project and cd Pandalyst then run the example.

**Comment by sauravm8** [comment]
Thanks, that worked.
