### ISSUE TITLE
Works well with 1 dataframe, few subsequent questions

### ISSUE THREAD

**Issue by sauravm8** [pipizhaoa/Pandalyst#2]
1. Is there any limit to the size of the dataframe it can handle?
2. What is the plan of handling multiple dataframes? Any timeline for that? 

Thanks for your great work.

**Comment by pipizhaoa** [comment]
1. Unlimited lines, large number of columns (max to ~20?) which is limited by the max length of the model (8192 in this case)
2. uncertain, supporting multiple dataframes is complex and requires significant investment. Before that, you can try to manually connect multiple tables.
